CREATE TABLE IF NOT EXISTS `avpn_6_ip` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`version` INT NOT NULL,
	`created` DATETIME NOT NULL,
	`modified` DATETIME NOT NULL,
	`ip` VARCHAR(45) NOT NULL UNIQUE,
	`type` INT NOT NULL,
	`cascade` BOOLEAN,
	`consensus` BOOLEAN,
	PRIMARY KEY( `id` )
);

CREATE TABLE IF NOT EXISTS `avpn_6_player` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`version` INT NOT NULL,
	`created` DATETIME NOT NULL,
	`modified` DATETIME NOT NULL,
	`uuid` VARCHAR(36) NOT NULL UNIQUE,
	`mcleaks` BOOLEAN NOT NULL,
	PRIMARY KEY( `id` )
);

CREATE TABLE IF NOT EXISTS `avpn_6_data` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`version` INT NOT NULL,
	`created` DATETIME NOT NULL,
	`modified` DATETIME NOT NULL,
	`key` VARCHAR(255) NOT NULL UNIQUE,
	`value` VARCHAR(255),
	PRIMARY KEY( `id` )
);