name: AntiVPN
main: me.egg82.antivpn.BukkitBootstrap
version: 5.12.0
author: egg82
api-version: 1.13
description: Get the best; save money on overpriced plugins and block VPN users!
softdepend: [Plan, PlaceholderAPI, Vault]
loadbefore: [Boss, Confiscate, CoreArena, ChatControl, AutoPlay, Winter, Puncher, AdvancedBan] # This is absolutely insane, but this somehow solves a random bug. Somehow.