name: AntiVPN
main: me.egg82.antivpn.BungeeBootstrap
version: 5.12.38
author: egg82
api-version: 1.13
description: Get the best; save money on overpriced plugins and block VPN users!
softdepend: [Plan, PlaceholderAPI]
# loadbefore AdvancedBan fixes false classloader warn issue for hsqldb - https://github.com/egg82/AntiVPN/issues/65
loadbefore: [AdvancedBan]