name: Build AntiVPN

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v1
    - name: Restore Maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Copy artifacts
      run: mkdir -p ./out/ && cp -t ./out/ **/target/*.jar
    - uses: actions/upload-artifact@v2
      with:
        name: Anti-VPN Jars
        path: out/
